src  += CryptoProvider.fs BCCryptoProvider.fs CSPCryptoProvider.fs OSSLCryptoProvider.fs CoreRandom.fsi CoreRandom.fs CoreKeys.fsi CoreKeys.fs CoreHash.fsi CoreHash.fs CoreCiphers.fsi CoreCiphers.fs CoreACiphers.fsi CoreACiphers.fs CoreHMac.fsi CoreHMac.fs CoreSig.fsi CoreSig.fs CoreDH.fsi CoreDH.fs
src7 += 
deps += 
