# -*- Makefile -*-

src    = \
	EchoImpl.fsi \
	EchoImpl.fs  \
	EchoTest.fs

deps   = ../bin/CoreCrypto.dll ../bin/TLSLib.dll ../bin/TLSStream.dll
target = ../bin/Echo.exe

.PHONY: all dist make.in

all: $(target)

dist:
	cp $(src) $(distdir)

make.in:
	@true

$(target): $(src) $(deps)
	$(fsc) $(fsflags) $(addprefix -r ,$(deps)) -o $@ $(src)

include ../Makefile.config
