# -*- Makefile -*-

# --------------------------------------------------------------------
arch = $(shell uname)

ifneq ($(findstring CYGWIN,$(arch)),)
buildtype = cygwin
ifneq ($(findstring WOW64,$(arch)),)
cygarch   = win64
else
ifneq ($(findstring x86,$(PROCESSOR_ARCHITECTURE)),)
cygarch   = win32
else
cygarch   = win64
endif
endif
else
buildtype = unix
cygarch   =
endif

# --------------------------------------------------------------------
ifeq ($(buildtype),unix)
msbuild := xbuild
z3exe   := z3
endif

ifeq ($(buildtype),cygwin)
ifeq ($(cygarch),win32)
msbuild := "/cygdrive/c/Program Files/MSBuild/12.0/Bin/MSBuild.exe"
else
msbuild := "/cygdrive/c/Program Files (x86)/MSBuild/12.0/Bin/MSBuild.exe"
endif

z3exe   := z3-$(cygarch:win%=x%).exe
endif

msbuild += /nologo

