# -*- Makefile -*-

# --------------------------------------------------------------------
TOP       = $(dir $(lastword $(filter %/Makefile.config,$(MAKEFILE_LIST))))
arch      = $(shell uname)
buildtype =

ifneq ($(findstring CYGWIN,$(arch)),)
buildtype = cygwin
else
buildtype = unix
endif

# --------------------------------------------------------------------
fslibs  := \
	FSharp.PowerPack.dll \
	FSharp.PowerPack.Compatibility.dll \
	System.Xml.dll \
	System.Security.dll

csflags := /nologo /lib:../bin
fsflags := --debug+ --optimize- --tailcalls- --crossoptimize- --mlcompatibility
fsflags += -I ../bin $(addprefix -r ,$(fslibs)) --nologo

include $(TOP)/Makefile.config.$(buildtype)
