# -*- Makefile -*-

# --------------------------------------------------------------------
arch = $(shell uname)

ifneq ($(findstring CYGWIN,$(arch)),)
buildtype = cygwin
ifneq ($(findstring WOW64,$(arch)),)
cygarch   = win64
else
cygarch   = win32
endif
else
buildtype = unix
cygarch   =
endif

# --------------------------------------------------------------------
ifeq ($(buildtype),unix)
msbuild := xbuild
z3exe   := z3
endif

ifeq ($(buildtype),cygwin)
fkkey := /HKLM/SOFTWARE/Microsoft/VisualStudio/SxS/VC7/FrameworkVer32
fkver := $(shell regtool get -W '$(fkkey)' 2>/dev/null | head -1)

ifeq ($(fkver),)
fkver := v4.0.30319
endif

msbuild := C:/Windows/Microsoft.NET/Framework/$(fkver)/MSBuild.exe
z3exe   := z3-$(cygarch:win%=x%).exe
endif

msbuild += /nologo

